# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=None, editable=False, help_text='Celery task ID', null=True)),
                ('status', django_fsm.FSMField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('finished', 'Finished'), ('aborted', 'Aborted'), ('errored', 'Error Occurred')], default='not_started', editable=False, max_length=50)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='pestle.Task')),
            ],
        ),
    ]
