# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_querylog_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='connection',
            field=models.CharField(blank=True, help_text='Name of DB connection (as specified in settings) to use for this query. Will use EXPLORER_DEFAULT_CONNECTION if left blank', max_length=128, null=True),
        ),
    ]
