sudo: required
language: python
cache: pip

python:
    - "3.6"

services:
    - elasticsearch
    - redis

stages:
    - lint
    - test

matrix:
    fast_finish: true

    include:
      - { stage: lint, env: TOXENV=lint, }
      - { stage: lint, env: TOXENV=isort, }

      - stage: test
        env: TOXENV=coverage
        addons:
            chrome: stable
        before_install:
            - pip install .
            - yurika-setup . --dev
        after_success:
            - pip install codecov && codecov

install:
    - pip install tox tox-travis tox-venv

script:
    - tox

notifications:
    email: false
