# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('urls', models.TextField(help_text='List of URLs to crawl (separated by newlines).')),
                ('block', models.TextField(blank=True, help_text='List of domains to block (separated by newlines.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=None, editable=False, help_text='Dramatiq message ID', null=True)),
                ('status', django_fsm.FSMField(choices=[('not_queued', 'Not queued'), ('enqueued', 'Waiting'), ('running', 'Running'), ('done', 'Finished'), ('failed', 'Failed'), ('aborted', 'Stopped')], default='not_queued', editable=False, max_length=50)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'base_manager_name': 'downcast',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('downcast', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('traceback', models.TextField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortar.Task')),
                ('revoked', models.BooleanField(default=False, editable=False, help_text='Task has been marked for revocation.')),
                ('crawler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='mortar.Crawler')),
            ],
            bases=('mortar.task',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('downcast', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='taskerror',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='mortar.Task'),
        ),
    ]
