# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mortar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceTokenizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('crawler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mortar.Crawler')),
            ],
        ),
    ]
