# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 15:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mortar', '0003_annotation_document_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='Override settings for Scrapy.', load_kwargs={}),
        ),
    ]
