# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errored',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortar.Task')),
            ],
            bases=('mortar.task',),
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortar.Task')),
                ('flag', models.BooleanField(default=False)),
            ],
            bases=('mortar.task',),
        ),
    ]
