from django.conf.urls import url
from . import views
urlpatterns = [
 url('^configure/$', views.configure, name='configure'),
 url('^execute/$', views.analyze, name='analyze'),
 url('^execute/start/(?P<pk>[\\d]+)/$', views.start_analysis, name="start-analysis"),
 url('^execute/stop/(?P<pk>[\\d]+)/$', views.stop_analysis, name="stop-analysis"),
 url('^execute/destroy/(?P<pk>[\\d]+)/$', views.destroy_analysis, name="destroy-analysis"),
 url('^status/execute/(?P<pk>[\\d]+)/$', views.analysis_status, name="analysis-status"),
 url('^crawler/start/(?P<pk>[\\d]+)/$', views.start_crawler, name="start-crawler"),
 url('^crawler/stop/(?P<pk>[\\d]+)/$', views.stop_crawler, name="stop-crawler"),
 url('^preprocess/start/(?P<pk>[\\d]+)/$', views.start_preprocess, name="start-preprocess"),
 url('^preprocess/stop/(?P<pk>[\\d]+)/$', views.stop_preprocess, name="stop-preprocess"),
 url('^query/start/(?P<pk>[\\d]+)/$', views.start_query, name="start-query"),
 url('^query/stop/(?P<pk>[\\d]+)/$', views.stop_query, name="stop-query"),
 url('^dictionaries/update/$', views.update_dictionaries, name='update-dicts'),
 url('^nodes/upload/(?P<pk>[\\d]+)/$', views.upload_mindmap, name="upload-mindmap"),
 url('^nodes/edit/(?P<pk>[\\d]+)/$', views.edit_node, name="edit-node-pk"),
 url('^nodes/edit/$', views.edit_node, name="edit-node"),
 url('^nodes/delete/$', views.delete_node, name="delete-node"),
 url('^nodes/delete/(?P<pk>[\\d]+)/$', views.delete_node, name="delete-node-pk"),
 url('^seeds/add/(?P<pk>[\\d]+)/$', views.add_seeds, name="add-seeds"),
 url('^seeds/edit/(?P<pk>[\\d]+)/$', views.edit_seed, name="edit-seed-pk"),
 url('^seeds/edit/$', views.edit_seed, name="edit-seed"),
 url('^seeds/delete/(?P<pk>[\\d]+)/$', views.delete_seed, name="delete-seed-pk"),
 url('^seeds/delete/$', views.delete_seed, name="delete-seed"),
 url('^dicts/add/$', views.add_dict, name="add-dict"),
 url('^dicts/edit/(?P<pk>[\\d]+)/$', views.edit_dict, name="edit-dict-pk"),
 url('^dicts/edit/$', views.edit_dict, name="edit-dict"),
 url('^dicts/delete/(?P<pk>[\\d]+)/$', views.delete_dict, name="delete-dict-pk"),
 url('^dicts/delete/$', views.delete_dict, name="delete-dict"),
 url('^queries/edit/(?P<pk>[\\d]+)/$', views.update_query, name="edit-query"),
 url('^$', views.home, name='home')
]
