# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(0, 'Crawling'), (1, 'Processing'), (2, 'Querying')])),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('msg', models.TextField()),
                ('error_type', models.CharField(blank=True, max_length=32, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='mortar.Analysis')),
            ],
        ),
    ]
