# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dictionaries',
                'verbose_name': 'Dictionary',
            },
        ),
        migrations.CreateModel(
            name='AIDictionaryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='mortar.AIDictionary')),
            ],
            options={
                'verbose_name_plural': 'Words',
                'verbose_name': 'Word',
            },
        ),
    ]
