# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortar', '0004_crawler_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawler',
            old_name='block',
            new_name='blocked_domains',
        ),
        migrations.RenameField(
            model_name='crawler',
            old_name='urls',
            new_name='start_urls',
        ),
    ]
